### ISSUE TITLE
Webcam enabled by default

### ISSUE THREAD

**Issue by LXNDRGLN** [ludiazv/octocitrico#9]
Hi, could you please provide a version for the OrangePi Zero with the webcam enabled by default or just enable it for all?

Is there a significant reason, why its not enabled by default?

**Comment by ludiazv** [comment]
Hi @LXNDRGLN,
   I do not plan to activate by default the cam service in the prebuild images as this is an optional service. Octoprint is functional without a cam.

  The reason is simple: Why start a service that is not needed that is going to consume limited resources and interfere with the rest of the system if not needed? Also using a web cam typically require some tuning and test of the configuration of the camera. See for example #8. In addition, is quite easy to start the service using the helper script referred in the documentation. It takes 1 minute to active it.

  The only reason I see to activate it is to use a standard image for several printers with custom configuration. In that case  you can build your custom image enabling the service by default if you want with a minor modification on the build script. Let me know if you need any assistance here let me know.

Best

**Comment by LXNDRGLN** [comment]
Hi @ludiazv 

Thanks a lot, i can understand your point!

I already started editing the `octopi.txt` file through `scripts/citrico-config` but I am not shure which `#` have to be removed and its looking like I got problems starting the `webcamd.service`.

Kind Regards

**Comment by ludiazv** [comment]
Check octoPi guide and to tune the camera config. here is goog post: https://iotrant.com/2020/02/25/properly-configuring-a-camera-in-octoprint/

Then to be sure enable the webcamd.service and reboot.

**Comment by LXNDRGLN** [comment]
Tanks a lot for your help, but I am struggeling with the installation as well as mentioned in #11 but on my OrangePi Zero the service is not starting and my changes in the `octopi.txt` are not saved after closing the windows with klicking on the `< OK >` button.

**Comment by ludiazv** [comment]
Can you edit the file ``/boot/octopi.txt`` with nano -> ``sudo nano /boot/octopi.txt``. Does it save the changes?

**Comment by LXNDRGLN** [comment]
if I am doing that the changes are saved yes but when I want to start the service with your scirpt it the bracets stay empty

**Comment by ludiazv** [comment]
If the helper script doesn't work well you can enable it in the command line.
```
$ sudo systemctl enable webcamd.service
(to enable the automatic start on sys init)
$ sudo systemctl start webcamd.service
(to start the service)
```

**Comment by madorax251** [comment]
what camera is compatible with the orange pi one? I used versions:
Armbian: 21.05.1
I have tried the Genius Eye 110 usb web cam but it doesn't work

**Comment by madorax251** [comment]
which is connected to the printer via otg because previously I tried to use the usb port when the printer is turned off the screen stays on

**Comment by LXNDRGLN** [comment]
I am not longer using my OrangePi Zeros, so I am closing this issue.
